/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CoursesIndexRouteImport } from './routes/courses/index'
import { Route as BlogIndexRouteImport } from './routes/blog/index'
import { Route as CoursesSlugRouteImport } from './routes/courses/$slug'
import { Route as BlogSlugRouteImport } from './routes/blog/$slug'
import { Route as AuthRegisterRouteImport } from './routes/auth/register'
import { Route as AuthLoginRouteImport } from './routes/auth/login'
import { Route as AuthForgotPasswordRouteImport } from './routes/auth/forgot-password'
import { Route as AdminLayoutRouteImport } from './routes/admin/_layout'
import { Route as AdminLayoutIndexRouteImport } from './routes/admin/_layout/index'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as AdminLayoutInvitationsRouteImport } from './routes/admin/_layout/invitations'
import { Route as AdminLayoutContentPreviewRouteImport } from './routes/admin/_layout/content-preview'
import { Route as AdminLayoutContentRouteImport } from './routes/admin/_layout/content'
import { Route as AdminLayoutUsersIndexRouteImport } from './routes/admin/_layout/users/index'
import { Route as AdminLayoutCoursesIndexRouteImport } from './routes/admin/_layout/courses/index'
import { Route as AdminLayoutBlogIndexRouteImport } from './routes/admin/_layout/blog/index'
import { Route as AdminLayoutUsersIdRouteImport } from './routes/admin/_layout/users/$id'
import { Route as AdminLayoutCoursesNewRouteImport } from './routes/admin/_layout/courses/new'
import { Route as AdminLayoutCoursesSlugRouteImport } from './routes/admin/_layout/courses/$slug'
import { Route as AdminLayoutBlogNewRouteImport } from './routes/admin/_layout/blog/new'
import { Route as AdminLayoutBlogSlugRouteImport } from './routes/admin/_layout/blog/$slug'
import { Route as AdminLayoutCoursesSlugLessonsRouteImport } from './routes/admin/_layout/courses/$slug/lessons'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CoursesIndexRoute = CoursesIndexRouteImport.update({
  id: '/courses/',
  path: '/courses/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const CoursesSlugRoute = CoursesSlugRouteImport.update({
  id: '/courses/$slug',
  path: '/courses/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRegisterRoute = AuthRegisterRouteImport.update({
  id: '/auth/register',
  path: '/auth/register',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthForgotPasswordRoute = AuthForgotPasswordRouteImport.update({
  id: '/auth/forgot-password',
  path: '/auth/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLayoutRoute = AdminLayoutRouteImport.update({
  id: '/admin/_layout',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLayoutIndexRoute = AdminLayoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminLayoutRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLayoutInvitationsRoute = AdminLayoutInvitationsRouteImport.update({
  id: '/invitations',
  path: '/invitations',
  getParentRoute: () => AdminLayoutRoute,
} as any)
const AdminLayoutContentPreviewRoute =
  AdminLayoutContentPreviewRouteImport.update({
    id: '/content-preview',
    path: '/content-preview',
    getParentRoute: () => AdminLayoutRoute,
  } as any)
const AdminLayoutContentRoute = AdminLayoutContentRouteImport.update({
  id: '/content',
  path: '/content',
  getParentRoute: () => AdminLayoutRoute,
} as any)
const AdminLayoutUsersIndexRoute = AdminLayoutUsersIndexRouteImport.update({
  id: '/users/',
  path: '/users/',
  getParentRoute: () => AdminLayoutRoute,
} as any)
const AdminLayoutCoursesIndexRoute = AdminLayoutCoursesIndexRouteImport.update({
  id: '/courses/',
  path: '/courses/',
  getParentRoute: () => AdminLayoutRoute,
} as any)
const AdminLayoutBlogIndexRoute = AdminLayoutBlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => AdminLayoutRoute,
} as any)
const AdminLayoutUsersIdRoute = AdminLayoutUsersIdRouteImport.update({
  id: '/users/$id',
  path: '/users/$id',
  getParentRoute: () => AdminLayoutRoute,
} as any)
const AdminLayoutCoursesNewRoute = AdminLayoutCoursesNewRouteImport.update({
  id: '/courses/new',
  path: '/courses/new',
  getParentRoute: () => AdminLayoutRoute,
} as any)
const AdminLayoutCoursesSlugRoute = AdminLayoutCoursesSlugRouteImport.update({
  id: '/courses/$slug',
  path: '/courses/$slug',
  getParentRoute: () => AdminLayoutRoute,
} as any)
const AdminLayoutBlogNewRoute = AdminLayoutBlogNewRouteImport.update({
  id: '/blog/new',
  path: '/blog/new',
  getParentRoute: () => AdminLayoutRoute,
} as any)
const AdminLayoutBlogSlugRoute = AdminLayoutBlogSlugRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => AdminLayoutRoute,
} as any)
const AdminLayoutCoursesSlugLessonsRoute =
  AdminLayoutCoursesSlugLessonsRouteImport.update({
    id: '/lessons',
    path: '/lessons',
    getParentRoute: () => AdminLayoutCoursesSlugRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminLayoutRouteWithChildren
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/courses/$slug': typeof CoursesSlugRoute
  '/blog/': typeof BlogIndexRoute
  '/courses/': typeof CoursesIndexRoute
  '/admin/content': typeof AdminLayoutContentRoute
  '/admin/content-preview': typeof AdminLayoutContentPreviewRoute
  '/admin/invitations': typeof AdminLayoutInvitationsRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/admin/': typeof AdminLayoutIndexRoute
  '/admin/blog/$slug': typeof AdminLayoutBlogSlugRoute
  '/admin/blog/new': typeof AdminLayoutBlogNewRoute
  '/admin/courses/$slug': typeof AdminLayoutCoursesSlugRouteWithChildren
  '/admin/courses/new': typeof AdminLayoutCoursesNewRoute
  '/admin/users/$id': typeof AdminLayoutUsersIdRoute
  '/admin/blog/': typeof AdminLayoutBlogIndexRoute
  '/admin/courses/': typeof AdminLayoutCoursesIndexRoute
  '/admin/users/': typeof AdminLayoutUsersIndexRoute
  '/admin/courses/$slug/lessons': typeof AdminLayoutCoursesSlugLessonsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/courses/$slug': typeof CoursesSlugRoute
  '/blog': typeof BlogIndexRoute
  '/courses': typeof CoursesIndexRoute
  '/admin/content': typeof AdminLayoutContentRoute
  '/admin/content-preview': typeof AdminLayoutContentPreviewRoute
  '/admin/invitations': typeof AdminLayoutInvitationsRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/admin': typeof AdminLayoutIndexRoute
  '/admin/blog/$slug': typeof AdminLayoutBlogSlugRoute
  '/admin/blog/new': typeof AdminLayoutBlogNewRoute
  '/admin/courses/$slug': typeof AdminLayoutCoursesSlugRouteWithChildren
  '/admin/courses/new': typeof AdminLayoutCoursesNewRoute
  '/admin/users/$id': typeof AdminLayoutUsersIdRoute
  '/admin/blog': typeof AdminLayoutBlogIndexRoute
  '/admin/courses': typeof AdminLayoutCoursesIndexRoute
  '/admin/users': typeof AdminLayoutUsersIndexRoute
  '/admin/courses/$slug/lessons': typeof AdminLayoutCoursesSlugLessonsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin/_layout': typeof AdminLayoutRouteWithChildren
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/courses/$slug': typeof CoursesSlugRoute
  '/blog/': typeof BlogIndexRoute
  '/courses/': typeof CoursesIndexRoute
  '/admin/_layout/content': typeof AdminLayoutContentRoute
  '/admin/_layout/content-preview': typeof AdminLayoutContentPreviewRoute
  '/admin/_layout/invitations': typeof AdminLayoutInvitationsRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/admin/_layout/': typeof AdminLayoutIndexRoute
  '/admin/_layout/blog/$slug': typeof AdminLayoutBlogSlugRoute
  '/admin/_layout/blog/new': typeof AdminLayoutBlogNewRoute
  '/admin/_layout/courses/$slug': typeof AdminLayoutCoursesSlugRouteWithChildren
  '/admin/_layout/courses/new': typeof AdminLayoutCoursesNewRoute
  '/admin/_layout/users/$id': typeof AdminLayoutUsersIdRoute
  '/admin/_layout/blog/': typeof AdminLayoutBlogIndexRoute
  '/admin/_layout/courses/': typeof AdminLayoutCoursesIndexRoute
  '/admin/_layout/users/': typeof AdminLayoutUsersIndexRoute
  '/admin/_layout/courses/$slug/lessons': typeof AdminLayoutCoursesSlugLessonsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/auth/forgot-password'
    | '/auth/login'
    | '/auth/register'
    | '/blog/$slug'
    | '/courses/$slug'
    | '/blog/'
    | '/courses/'
    | '/admin/content'
    | '/admin/content-preview'
    | '/admin/invitations'
    | '/api/auth/$'
    | '/admin/'
    | '/admin/blog/$slug'
    | '/admin/blog/new'
    | '/admin/courses/$slug'
    | '/admin/courses/new'
    | '/admin/users/$id'
    | '/admin/blog/'
    | '/admin/courses/'
    | '/admin/users/'
    | '/admin/courses/$slug/lessons'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth/forgot-password'
    | '/auth/login'
    | '/auth/register'
    | '/blog/$slug'
    | '/courses/$slug'
    | '/blog'
    | '/courses'
    | '/admin/content'
    | '/admin/content-preview'
    | '/admin/invitations'
    | '/api/auth/$'
    | '/admin'
    | '/admin/blog/$slug'
    | '/admin/blog/new'
    | '/admin/courses/$slug'
    | '/admin/courses/new'
    | '/admin/users/$id'
    | '/admin/blog'
    | '/admin/courses'
    | '/admin/users'
    | '/admin/courses/$slug/lessons'
  id:
    | '__root__'
    | '/'
    | '/admin/_layout'
    | '/auth/forgot-password'
    | '/auth/login'
    | '/auth/register'
    | '/blog/$slug'
    | '/courses/$slug'
    | '/blog/'
    | '/courses/'
    | '/admin/_layout/content'
    | '/admin/_layout/content-preview'
    | '/admin/_layout/invitations'
    | '/api/auth/$'
    | '/admin/_layout/'
    | '/admin/_layout/blog/$slug'
    | '/admin/_layout/blog/new'
    | '/admin/_layout/courses/$slug'
    | '/admin/_layout/courses/new'
    | '/admin/_layout/users/$id'
    | '/admin/_layout/blog/'
    | '/admin/_layout/courses/'
    | '/admin/_layout/users/'
    | '/admin/_layout/courses/$slug/lessons'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminLayoutRoute: typeof AdminLayoutRouteWithChildren
  AuthForgotPasswordRoute: typeof AuthForgotPasswordRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthRegisterRoute: typeof AuthRegisterRoute
  BlogSlugRoute: typeof BlogSlugRoute
  CoursesSlugRoute: typeof CoursesSlugRoute
  BlogIndexRoute: typeof BlogIndexRoute
  CoursesIndexRoute: typeof CoursesIndexRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/courses/': {
      id: '/courses/'
      path: '/courses'
      fullPath: '/courses/'
      preLoaderRoute: typeof CoursesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/': {
      id: '/blog/'
      path: '/blog'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/courses/$slug': {
      id: '/courses/$slug'
      path: '/courses/$slug'
      fullPath: '/courses/$slug'
      preLoaderRoute: typeof CoursesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/register': {
      id: '/auth/register'
      path: '/auth/register'
      fullPath: '/auth/register'
      preLoaderRoute: typeof AuthRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/forgot-password': {
      id: '/auth/forgot-password'
      path: '/auth/forgot-password'
      fullPath: '/auth/forgot-password'
      preLoaderRoute: typeof AuthForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/_layout': {
      id: '/admin/_layout'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/_layout/': {
      id: '/admin/_layout/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminLayoutIndexRouteImport
      parentRoute: typeof AdminLayoutRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/_layout/invitations': {
      id: '/admin/_layout/invitations'
      path: '/invitations'
      fullPath: '/admin/invitations'
      preLoaderRoute: typeof AdminLayoutInvitationsRouteImport
      parentRoute: typeof AdminLayoutRoute
    }
    '/admin/_layout/content-preview': {
      id: '/admin/_layout/content-preview'
      path: '/content-preview'
      fullPath: '/admin/content-preview'
      preLoaderRoute: typeof AdminLayoutContentPreviewRouteImport
      parentRoute: typeof AdminLayoutRoute
    }
    '/admin/_layout/content': {
      id: '/admin/_layout/content'
      path: '/content'
      fullPath: '/admin/content'
      preLoaderRoute: typeof AdminLayoutContentRouteImport
      parentRoute: typeof AdminLayoutRoute
    }
    '/admin/_layout/users/': {
      id: '/admin/_layout/users/'
      path: '/users'
      fullPath: '/admin/users/'
      preLoaderRoute: typeof AdminLayoutUsersIndexRouteImport
      parentRoute: typeof AdminLayoutRoute
    }
    '/admin/_layout/courses/': {
      id: '/admin/_layout/courses/'
      path: '/courses'
      fullPath: '/admin/courses/'
      preLoaderRoute: typeof AdminLayoutCoursesIndexRouteImport
      parentRoute: typeof AdminLayoutRoute
    }
    '/admin/_layout/blog/': {
      id: '/admin/_layout/blog/'
      path: '/blog'
      fullPath: '/admin/blog/'
      preLoaderRoute: typeof AdminLayoutBlogIndexRouteImport
      parentRoute: typeof AdminLayoutRoute
    }
    '/admin/_layout/users/$id': {
      id: '/admin/_layout/users/$id'
      path: '/users/$id'
      fullPath: '/admin/users/$id'
      preLoaderRoute: typeof AdminLayoutUsersIdRouteImport
      parentRoute: typeof AdminLayoutRoute
    }
    '/admin/_layout/courses/new': {
      id: '/admin/_layout/courses/new'
      path: '/courses/new'
      fullPath: '/admin/courses/new'
      preLoaderRoute: typeof AdminLayoutCoursesNewRouteImport
      parentRoute: typeof AdminLayoutRoute
    }
    '/admin/_layout/courses/$slug': {
      id: '/admin/_layout/courses/$slug'
      path: '/courses/$slug'
      fullPath: '/admin/courses/$slug'
      preLoaderRoute: typeof AdminLayoutCoursesSlugRouteImport
      parentRoute: typeof AdminLayoutRoute
    }
    '/admin/_layout/blog/new': {
      id: '/admin/_layout/blog/new'
      path: '/blog/new'
      fullPath: '/admin/blog/new'
      preLoaderRoute: typeof AdminLayoutBlogNewRouteImport
      parentRoute: typeof AdminLayoutRoute
    }
    '/admin/_layout/blog/$slug': {
      id: '/admin/_layout/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/admin/blog/$slug'
      preLoaderRoute: typeof AdminLayoutBlogSlugRouteImport
      parentRoute: typeof AdminLayoutRoute
    }
    '/admin/_layout/courses/$slug/lessons': {
      id: '/admin/_layout/courses/$slug/lessons'
      path: '/lessons'
      fullPath: '/admin/courses/$slug/lessons'
      preLoaderRoute: typeof AdminLayoutCoursesSlugLessonsRouteImport
      parentRoute: typeof AdminLayoutCoursesSlugRoute
    }
  }
}

interface AdminLayoutCoursesSlugRouteChildren {
  AdminLayoutCoursesSlugLessonsRoute: typeof AdminLayoutCoursesSlugLessonsRoute
}

const AdminLayoutCoursesSlugRouteChildren: AdminLayoutCoursesSlugRouteChildren =
  {
    AdminLayoutCoursesSlugLessonsRoute: AdminLayoutCoursesSlugLessonsRoute,
  }

const AdminLayoutCoursesSlugRouteWithChildren =
  AdminLayoutCoursesSlugRoute._addFileChildren(
    AdminLayoutCoursesSlugRouteChildren,
  )

interface AdminLayoutRouteChildren {
  AdminLayoutContentRoute: typeof AdminLayoutContentRoute
  AdminLayoutContentPreviewRoute: typeof AdminLayoutContentPreviewRoute
  AdminLayoutInvitationsRoute: typeof AdminLayoutInvitationsRoute
  AdminLayoutIndexRoute: typeof AdminLayoutIndexRoute
  AdminLayoutBlogSlugRoute: typeof AdminLayoutBlogSlugRoute
  AdminLayoutBlogNewRoute: typeof AdminLayoutBlogNewRoute
  AdminLayoutCoursesSlugRoute: typeof AdminLayoutCoursesSlugRouteWithChildren
  AdminLayoutCoursesNewRoute: typeof AdminLayoutCoursesNewRoute
  AdminLayoutUsersIdRoute: typeof AdminLayoutUsersIdRoute
  AdminLayoutBlogIndexRoute: typeof AdminLayoutBlogIndexRoute
  AdminLayoutCoursesIndexRoute: typeof AdminLayoutCoursesIndexRoute
  AdminLayoutUsersIndexRoute: typeof AdminLayoutUsersIndexRoute
}

const AdminLayoutRouteChildren: AdminLayoutRouteChildren = {
  AdminLayoutContentRoute: AdminLayoutContentRoute,
  AdminLayoutContentPreviewRoute: AdminLayoutContentPreviewRoute,
  AdminLayoutInvitationsRoute: AdminLayoutInvitationsRoute,
  AdminLayoutIndexRoute: AdminLayoutIndexRoute,
  AdminLayoutBlogSlugRoute: AdminLayoutBlogSlugRoute,
  AdminLayoutBlogNewRoute: AdminLayoutBlogNewRoute,
  AdminLayoutCoursesSlugRoute: AdminLayoutCoursesSlugRouteWithChildren,
  AdminLayoutCoursesNewRoute: AdminLayoutCoursesNewRoute,
  AdminLayoutUsersIdRoute: AdminLayoutUsersIdRoute,
  AdminLayoutBlogIndexRoute: AdminLayoutBlogIndexRoute,
  AdminLayoutCoursesIndexRoute: AdminLayoutCoursesIndexRoute,
  AdminLayoutUsersIndexRoute: AdminLayoutUsersIndexRoute,
}

const AdminLayoutRouteWithChildren = AdminLayoutRoute._addFileChildren(
  AdminLayoutRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminLayoutRoute: AdminLayoutRouteWithChildren,
  AuthForgotPasswordRoute: AuthForgotPasswordRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthRegisterRoute: AuthRegisterRoute,
  BlogSlugRoute: BlogSlugRoute,
  CoursesSlugRoute: CoursesSlugRoute,
  BlogIndexRoute: BlogIndexRoute,
  CoursesIndexRoute: CoursesIndexRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
