import { useCallback, useEffect, useRef, useState } from "react";

import { useDevultur, useVideoState } from "@devultur/convex/react";
import type { DevulturMedia } from "@devultur/core";
import { formatTime, TranscriptPanel, UploadZone, VideoPlayer, type VideoPlayerRef } from "@devultur/react";
import { useForm } from "@tanstack/react-form";
import { useAction, useMutation } from "convex/react";
import { CheckCircle2, Clock, Download, Film, Loader2, Sparkles, Upload, X } from "lucide-react";
import { motion } from "motion/react";
import { z } from "zod";

import { api } from "@convex/_generated/api";
import type { Doc, Id } from "@convex/_generated/dataModel";
import { Badge } from "@repo/ui/components/badge";
import { Button } from "@repo/ui/components/button";
import { Label } from "@repo/ui/components/label";
import { slugify } from "@repo/utils";

import { FormField } from "#/components/form-field";
import { SmartSubmit } from "#/components/smart-submit";
import { usePulse, useSubmitPulse } from "#/lib/form-primitives";
import { uploadErrorMessage } from "#/lib/upload-error";

const lessonSchema = z.object({
  title: z.string().min(3, "Mínimo 3 caracteres"),
  description: z.string(),
});

const SUBMIT_ID = "lesson-submit";
const fieldLabels: Record<string, string> = { title: "Título" };

const CAPTION_LABELS: Record<string, string> = { "es-CO": "Español (CO)", en: "English" };
const CAPTION_LOCALES = ["es-CO", "en"];
const STEP_LABELS: Record<string, string> = {
  downloading: "Descargando",
  encoding: "Codificando",
  uploading: "Subiendo",
  captioning: "Generando subtítulos",
};

function generateLessonSlug(courseSlug: string, lessonNumber: number, title: string): string {
  const num = String(lessonNumber).padStart(2, "0");
  return `${courseSlug}-${num}-${slugify(title)}`;
}

interface LessonFormProps {
  courseId: Id<"courses">;
  courseSlug: string;
  lessonCount: number;
  lesson?: Doc<"lessons">;
  onDone: () => void;
}

export function LessonForm({ courseId, courseSlug, lessonCount, lesson, onDone }: LessonFormProps) {
  const createLesson = useMutation(api.lessons.create);
  const updateLesson = useMutation(api.lessons.update);
  const translateAction = useAction(api.ai.translateText);
  const generateMetadataAction = useAction(api.ai.generateLessonMetadata);
  const processVideoAction = useAction(api.devultur.processVideo);

  const isEditing = !!lesson;
  const hasExistingVideo = isEditing && !!lesson.video;

  const [isFree, setIsFree] = useState(lesson?.isFree ?? false);
  const [video, setVideo] = useState<DevulturMedia | null>(lesson?.video ?? null);
  const [uploadedFileName, setUploadedFileName] = useState<string | null>(null);
  const [uploadError, setUploadError] = useState<string | null>(null);
  const [serverError, setServerError] = useState("");
  const [savedAsDraft, setSavedAsDraft] = useState(false);
  const [generatingMeta, setGeneratingMeta] = useState(false);
  const hasAutoGenerated = useRef(false);
  const playerRef = useRef<VideoPlayerRef>(null);
  const [activeSubLocale, setActiveSubLocale] = useState<string>("es-CO");
  const [currentTime, setCurrentTime] = useState(0);
  const draftLessonIdRef = useRef<Id<"lessons"> | null>(lesson?._id ?? null);
  const previousVideoRef = useRef<DevulturMedia | null>(lesson?.video ?? null);
  // Stashes the raw upload key + assembled ref between UploadZone's onUploadUrl and onComplete.
  const pendingUploadRef = useRef<{ key: string; media: DevulturMedia } | null>(null);
  const submitControls = useSubmitPulse(SUBMIT_ID);

  const { getCaptionsText, deleteMedia: deleteMediaFn } = useDevultur();
  const createUploadUrlAction = useAction(api.devultur.createUploadUrl);

  // Typed video state: idle → queued → processing → ready | failed (exhaustive switch below).
  const videoState = useVideoState(video, { locales: CAPTION_LOCALES });
  const captionTracks = videoState.phase === "ready" ? videoState.captions : [];
  const captionLocales = captionTracks.map((c) => c.locale);
  const duration = videoState.phase === "ready" ? videoState.duration : 0;
  const playerToken = videoState.phase === "ready" ? videoState.playerProps.token : undefined;

  // Auto-generate metadata when captions become available (auth-transparent, no manual token).
  const generateMetadata = useCallback(async () => {
    if (!video || generatingMeta || !captionLocales.includes("es-CO")) return;

    setGeneratingMeta(true);
    try {
      const vttText = await getCaptionsText(video, "es-CO");
      const plainText = vttText
        .split("\n")
        .filter(
          (line) => !line.includes("-->") && !line.match(/^\d+$/) && line.trim() !== "" && !line.startsWith("WEBVTT"),
        )
        .join(" ");

      const result = await generateMetadataAction({ transcript: plainText });
      if (result.title) form.setFieldValue("title", result.title);
      if (result.description) form.setFieldValue("description", result.description);
    } catch {}
    setGeneratingMeta(false);
  }, [video, captionLocales, generatingMeta, getCaptionsText, generateMetadataAction]);

  useEffect(() => {
    if (hasAutoGenerated.current || isEditing) return;
    if (!captionLocales.includes("es-CO")) return;
    hasAutoGenerated.current = true;
    generateMetadata();
  }, [captionLocales, isEditing, generateMetadata]);

  const handleUploadUrl = async (file: File) => {
    const res = await createUploadUrlAction({ filename: file.name, contentType: file.type, visibility: "private" });
    pendingUploadRef.current = {
      key: res.key,
      media: { id: res.id, kind: "video", visibility: "private", filename: file.name },
    };
    return { url: res.url, key: res.key };
  };

  const form = useForm({
    defaultValues: {
      title: lesson?.title.es ?? "",
      description: lesson?.description?.es ?? "",
    },
    validators: { onChange: lessonSchema },
    onSubmit: async ({ value }) => {
      setServerError("");
      try {
        const [titleResult, descResult] = await Promise.all([
          translateAction({ text: value.title }),
          value.description ? translateAction({ text: value.description }) : null,
        ]);

        const titleEn = titleResult.translated || value.title;
        const descEn = descResult?.translated || value.description || value.title;
        const lessonSlug = generateLessonSlug(courseSlug, lessonCount + 1, value.title);

        const lessonId = draftLessonIdRef.current ?? lesson?._id;
        if (lessonId) {
          await updateLesson({
            lessonId,
            title: { es: value.title, en: titleEn },
            slug: lessonSlug,
            description: { es: value.description, en: descEn },
            isFree,
          });
        } else {
          await createLesson({
            courseId,
            title: { es: value.title, en: titleEn },
            slug: lessonSlug,
            description: { es: value.description, en: descEn },
            video: video ?? undefined,
            isFree,
          });
        }
        onDone();
      } catch (err: any) {
        setServerError(err.message ?? "Error al guardar");
      }
    },
  });

  const saveDraft = useCallback(
    async (newMedia: DevulturMedia, key: string) => {
      const rawTitle = form.getFieldValue("title");
      const titleEs = rawTitle && rawTitle.length >= 3 ? rawTitle : "Lección sin nombrar";
      if (!rawTitle || rawTitle.length < 3) {
        form.setFieldValue("title", titleEs);
      }

      try {
        const titleEn =
          titleEs === "Lección sin nombrar"
            ? "Untitled lesson"
            : (await translateAction({ text: titleEs })).translated || titleEs;

        if (isEditing) {
          await updateLesson({ lessonId: lesson._id, video: newMedia });
          draftLessonIdRef.current = lesson._id;
        } else {
          const newId = await createLesson({
            courseId,
            title: { es: titleEs, en: titleEn },
            description: { es: "", en: "" },
            video: newMedia,
            isFree: false,
          });
          draftLessonIdRef.current = newId as Id<"lessons">;
        }
        setSavedAsDraft(true);

        processVideoAction({ key }).catch(() => {});
      } catch {}
    },
    [
      courseId,
      isEditing,
      lesson,
      createLesson,
      updateLesson,
      translateAction,
      processVideoAction,
      form.getFieldValue,
      form.setFieldValue,
    ],
  );

  const handleUploadComplete = (result: { key: string; file: File }) => {
    const pending = pendingUploadRef.current;
    if (!pending || pending.key !== result.key) return;
    const newMedia = pending.media;

    if (previousVideoRef.current) {
      deleteMediaFn(previousVideoRef.current);
    }
    previousVideoRef.current = newMedia;

    setVideo(newMedia);
    setUploadedFileName(result.file.name);
    setUploadError(null);

    saveDraft(newMedia, pending.key);
  };

  const hasUploadedVideo = !!video;

  return (
    <div className="bg-muted p-6 mb-6">
      <div className="flex items-center justify-between mb-4">
        <div className="flex items-center gap-3">
          <h3 className="font-semibold">{isEditing ? "Editar lección" : "Nueva lección"}</h3>
          {savedAsDraft && (
            <Badge variant="outline" className="text-xs text-amber-600 border-amber-300">
              Borrador guardado
            </Badge>
          )}
          {generatingMeta && (
            <span className="flex items-center gap-1 text-xs text-muted-foreground">
              <Loader2 className="size-3 animate-spin" />
              Generando metadatos...
            </span>
          )}
        </div>
        <div className="flex items-center gap-1">
          <Button
            type="button"
            variant="ghost"
            size="icon-sm"
            onClick={generateMetadata}
            disabled={generatingMeta || !captionLocales.includes("es-CO")}
            title="Generar título y descripción desde la transcripción"
          >
            {generatingMeta ? <Loader2 className="size-4 animate-spin" /> : <Sparkles className="size-4" />}
          </Button>
          <Button type="button" variant="ghost" size="icon-sm" onClick={onDone}>
            <X className="size-4" />
          </Button>
        </div>
      </div>
      <form
        onSubmit={(e) => {
          e.preventDefault();
          form.handleSubmit();
        }}
        className="space-y-4"
      >
        <label className="flex items-center gap-2 cursor-pointer">
          <input
            type="checkbox"
            checked={isFree}
            onChange={(e) => setIsFree(e.target.checked)}
            className="accent-foreground"
          />
          <span className="text-sm font-medium">Lección gratuita</span>
        </label>

        <form.Field
          name="title"
          children={(field) => (
            <FormField
              field={field}
              label="Título"
              placeholder="Preparación de la piel"
              autoFocus
              nextFieldId="description"
              submitId={SUBMIT_ID}
            />
          )}
        />

        <form.Field name="description" children={(field) => <LessonDescriptionField field={field} />} />

        <div>
          <Label className="text-xs uppercase tracking-wider font-medium mb-2 block">Video</Label>

          {videoState.phase === "ready" && (
            <div
              className="mb-3 rounded-md overflow-hidden border border-border bg-black"
              style={{ aspectRatio: "16/9", maxHeight: "18rem" }}
            >
              <VideoPlayer
                ref={playerRef}
                {...videoState.playerProps}
                defaultCaption="es-CO"
                aspectRatio="16/9"
                onProgress={(time) => setCurrentTime(time)}
              />
            </div>
          )}

          {duration > 0 && (
            <div className="flex items-center gap-1.5 text-sm text-muted-foreground mb-2">
              <Clock className="size-3.5" />
              <span>Duración: {formatTime(duration)}</span>
            </div>
          )}

          {hasUploadedVideo || hasExistingVideo ? (
            <div className="flex items-center gap-2 p-2 border border-border rounded-md bg-background mb-2">
              <Film className="size-4 text-muted-foreground shrink-0" />
              <span className="text-sm truncate flex-1">{uploadedFileName ?? lesson?.video?.filename ?? "Video"}</span>
              {videoState.phase === "queued" && (
                <div className="flex items-center gap-1.5 text-xs text-amber-600 shrink-0">
                  <Loader2 className="size-3 animate-spin" />
                  Solicitando transcodificación…
                </div>
              )}
              {videoState.phase === "processing" && (
                <div className="flex items-center gap-1.5 text-xs text-amber-600 shrink-0">
                  <Loader2 className="size-3 animate-spin" />
                  {STEP_LABELS[videoState.step] ?? "Procesando"} {videoState.percent}%
                </div>
              )}
              {videoState.phase === "ready" && <CheckCircle2 className="size-4 text-green-500 shrink-0" />}
              {videoState.phase === "failed" && (
                <span className="text-xs text-red-500 shrink-0">{videoState.message}</span>
              )}
            </div>
          ) : (
            <UploadZone
              onUploadUrl={handleUploadUrl}
              onComplete={handleUploadComplete}
              onError={(err) => setUploadError(uploadErrorMessage(err))}
              accept={["video/mp4", "video/quicktime", "video/webm"]}
            >
              {({ getRootProps, getInputProps, isDragging, isUploading, progress, file: uploadFile }) => (
                <div
                  {...getRootProps()}
                  className={`relative flex flex-col items-center justify-center gap-2 p-6 border border-dashed rounded-md cursor-pointer transition-colors ${
                    isDragging
                      ? "border-foreground/50 bg-foreground/5"
                      : "border-muted-foreground/30 hover:border-muted-foreground/50 bg-background"
                  }`}
                >
                  <input {...getInputProps()} />
                  {isUploading ? (
                    <>
                      <Loader2 className="size-6 animate-spin text-muted-foreground" />
                      <p className="text-sm text-muted-foreground">
                        Subiendo {uploadFile?.name}... {Math.round(progress)}%
                      </p>
                      <div className="w-full max-w-xs h-1.5 bg-muted rounded-full overflow-hidden">
                        <div
                          className="h-full bg-foreground rounded-full transition-all duration-300"
                          style={{ width: `${progress}%` }}
                        />
                      </div>
                    </>
                  ) : (
                    <>
                      <Upload className="size-6 text-muted-foreground" />
                      <p className="text-sm text-muted-foreground">
                        {isDragging ? "Suelta el video aquí" : "Arrastra un video o haz clic para seleccionar"}
                      </p>
                      <p className="text-xs text-muted-foreground/60">MP4, MOV o WebM · Máximo 2GB</p>
                    </>
                  )}
                </div>
              )}
            </UploadZone>
          )}
          {uploadError && <p className="text-sm text-red-500 mt-1">{uploadError}</p>}
        </div>

        {captionTracks.length > 0 && (
          <div>
            <div className="flex items-center justify-between mb-2">
              <div className="flex items-center gap-2">
                <Label className="text-xs uppercase tracking-wider font-medium block">Subtítulos</Label>
                <span className="text-xs text-muted-foreground">
                  {CAPTION_LABELS[activeSubLocale] ?? activeSubLocale}
                </span>
              </div>
              <div className="flex items-center gap-1">
                {captionLocales.map((locale) => (
                  <Button
                    key={locale}
                    type="button"
                    variant={activeSubLocale === locale ? "default" : "outline"}
                    size="xs"
                    onClick={() => setActiveSubLocale(locale)}
                  >
                    {locale === "es-CO" ? "ES" : locale.toUpperCase()}
                  </Button>
                ))}
                {video && captionLocales.includes(activeSubLocale) && (
                  <Button
                    type="button"
                    variant="ghost"
                    size="xs"
                    onClick={async () => {
                      const text = await getCaptionsText(video, activeSubLocale);
                      const blob = new Blob([text], { type: "text/vtt" });
                      const href = URL.createObjectURL(blob);
                      const a = document.createElement("a");
                      a.href = href;
                      a.download = `${activeSubLocale}.vtt`;
                      a.click();
                      URL.revokeObjectURL(href);
                    }}
                  >
                    <Download className="size-3" />
                  </Button>
                )}
              </div>
            </div>
            <TranscriptPanel
              captions={captionTracks}
              locale={activeSubLocale}
              currentTime={currentTime}
              token={playerToken}
              onSeek={(seconds) => {
                playerRef.current?.seek(seconds);
                playerRef.current?.play();
              }}
            />
          </div>
        )}

        {serverError && <p className="text-sm text-destructive">{serverError}</p>}

        <p className="text-xs text-muted-foreground">La traducción al inglés se genera automáticamente al guardar.</p>

        <form.Subscribe
          selector={(state) => [state.isSubmitting, state.canSubmit, state.isPristine, state.values] as const}
          children={([isSubmitting, canSubmit, isPristine, values]) => {
            const isDisabled = isSubmitting || !canSubmit || (isPristine && !video && !savedAsDraft);
            const emptyFields = Object.entries(values as Record<string, string>)
              .filter(([k, v]) => !v && k !== "description")
              .map(([k]) => fieldLabels[k] ?? k);

            return (
              <div className="flex gap-3 items-start">
                <div className="flex-1">
                  <SmartSubmit
                    id={SUBMIT_ID}
                    controls={submitControls}
                    isSubmitting={isSubmitting}
                    isDisabled={isDisabled}
                    emptyFieldLabels={emptyFields}
                    label={isEditing || savedAsDraft ? "Guardar cambios" : "Agregar lección"}
                    submittingLabel="Traduciendo y guardando..."
                  />
                </div>
                <Button type="button" variant="ghost" className="h-11" onClick={onDone}>
                  Cancelar
                </Button>
              </div>
            );
          }}
        />
      </form>
    </div>
  );
}

function LessonDescriptionField({ field }: { field: any }) {
  const hasError = field.state.meta.isTouched && field.state.meta.errors.length > 0;
  const errorMessage = hasError ? (field.state.meta.errors[0]?.message ?? field.state.meta.errors[0]) : null;
  const controls = usePulse(field.name);

  return (
    <motion.div animate={controls}>
      <Label htmlFor="description" className="text-xs uppercase tracking-wider font-medium mb-1 block">
        Descripción <span className="text-muted-foreground font-normal normal-case tracking-normal">(opcional)</span>
      </Label>
      <textarea
        id="description"
        value={field.state.value}
        onChange={(e) => field.handleChange(e.target.value)}
        onBlur={field.handleBlur}
        placeholder="Descripción breve de la lección"
        className="flex field-sizing-content min-h-16 w-full rounded-none border-0 border-b border-input bg-transparent px-0 py-2 transition-colors outline-none placeholder:text-muted-foreground/60 focus-visible:border-foreground/40"
      />
      {errorMessage && <p className="text-sm text-destructive mt-1">{errorMessage}</p>}
    </motion.div>
  );
}
