/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VideoCostsRouteImport } from './routes/video-costs'
import { Route as QuoteRouteImport } from './routes/quote'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as PlanRouteImport } from './routes/plan'
import { Route as BunnyVsR2RouteImport } from './routes/bunny-vs-r2'
import { Route as BunnyRoadmapRouteImport } from './routes/bunny-roadmap'
import { Route as IndexRouteImport } from './routes/index'

const VideoCostsRoute = VideoCostsRouteImport.update({
  id: '/video-costs',
  path: '/video-costs',
  getParentRoute: () => rootRouteImport,
} as any)
const QuoteRoute = QuoteRouteImport.update({
  id: '/quote',
  path: '/quote',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const PlanRoute = PlanRouteImport.update({
  id: '/plan',
  path: '/plan',
  getParentRoute: () => rootRouteImport,
} as any)
const BunnyVsR2Route = BunnyVsR2RouteImport.update({
  id: '/bunny-vs-r2',
  path: '/bunny-vs-r2',
  getParentRoute: () => rootRouteImport,
} as any)
const BunnyRoadmapRoute = BunnyRoadmapRouteImport.update({
  id: '/bunny-roadmap',
  path: '/bunny-roadmap',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/bunny-roadmap': typeof BunnyRoadmapRoute
  '/bunny-vs-r2': typeof BunnyVsR2Route
  '/plan': typeof PlanRoute
  '/pricing': typeof PricingRoute
  '/quote': typeof QuoteRoute
  '/video-costs': typeof VideoCostsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/bunny-roadmap': typeof BunnyRoadmapRoute
  '/bunny-vs-r2': typeof BunnyVsR2Route
  '/plan': typeof PlanRoute
  '/pricing': typeof PricingRoute
  '/quote': typeof QuoteRoute
  '/video-costs': typeof VideoCostsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/bunny-roadmap': typeof BunnyRoadmapRoute
  '/bunny-vs-r2': typeof BunnyVsR2Route
  '/plan': typeof PlanRoute
  '/pricing': typeof PricingRoute
  '/quote': typeof QuoteRoute
  '/video-costs': typeof VideoCostsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/bunny-roadmap'
    | '/bunny-vs-r2'
    | '/plan'
    | '/pricing'
    | '/quote'
    | '/video-costs'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/bunny-roadmap'
    | '/bunny-vs-r2'
    | '/plan'
    | '/pricing'
    | '/quote'
    | '/video-costs'
  id:
    | '__root__'
    | '/'
    | '/bunny-roadmap'
    | '/bunny-vs-r2'
    | '/plan'
    | '/pricing'
    | '/quote'
    | '/video-costs'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BunnyRoadmapRoute: typeof BunnyRoadmapRoute
  BunnyVsR2Route: typeof BunnyVsR2Route
  PlanRoute: typeof PlanRoute
  PricingRoute: typeof PricingRoute
  QuoteRoute: typeof QuoteRoute
  VideoCostsRoute: typeof VideoCostsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/video-costs': {
      id: '/video-costs'
      path: '/video-costs'
      fullPath: '/video-costs'
      preLoaderRoute: typeof VideoCostsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quote': {
      id: '/quote'
      path: '/quote'
      fullPath: '/quote'
      preLoaderRoute: typeof QuoteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plan': {
      id: '/plan'
      path: '/plan'
      fullPath: '/plan'
      preLoaderRoute: typeof PlanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bunny-vs-r2': {
      id: '/bunny-vs-r2'
      path: '/bunny-vs-r2'
      fullPath: '/bunny-vs-r2'
      preLoaderRoute: typeof BunnyVsR2RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bunny-roadmap': {
      id: '/bunny-roadmap'
      path: '/bunny-roadmap'
      fullPath: '/bunny-roadmap'
      preLoaderRoute: typeof BunnyRoadmapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BunnyRoadmapRoute: BunnyRoadmapRoute,
  BunnyVsR2Route: BunnyVsR2Route,
  PlanRoute: PlanRoute,
  PricingRoute: PricingRoute,
  QuoteRoute: QuoteRoute,
  VideoCostsRoute: VideoCostsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
